# Generated by Django 3.2.15 on 2023-10-12 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0002_postcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcard',
            name='title',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
