# Generated by Django 3.2.15 on 2023-10-13 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0003_alter_postcard_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='project',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='user_note',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Todo',
        ),
    ]
